name: mobile-deploy-ci

on:
  push:
    branches:
      - master
    paths:
      - 'src/mobile/**'

jobs:
  # Confirm that prettier was run on the changes
  prettier:
    uses: Seneca-CDOT/telescope/.github/workflows/prettier-ci.yml@master

  # Make sure eslint passes
  eslint:
    uses: Seneca-CDOT/telescope/.github/workflows/eslint-ci.yml@master
    secrets:
      server-token: ${{ secrets.TURBO_SERVER_TOKEN }}

  publish:
    needs: [prettier, eslint]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - name: ğŸ“¦ Install dependencies
        run: pnpm install
      - name: ğŸš€ Publish app
        run: |
          cd src/mobile
          expo publish --non-interactive
